### ISSUE TITLE
Missing iam:PassRole documentation in a bunch of ARC pages and actions

### ISSUE THREAD

**Issue by copumpkin** [awsdocs/iam-user-guide#104]
Sorry to keep submitting these ARC issues here but there's not really a good place for me to submit them otherwise!

A handful of ARC pages for services include `iam:PassRole` as a dependent action, but it seems like most actions that depend on `iam:PassRole` don't list it as a dependent action. As usual, this is due to missing data from all the service-specific permission data files, but given that it's so pervasive across different services, it's also probably relevant to IAM.

Here's a few common ones off the top of my head that aren't listed on the ARC pages:

1. `ec2:RunInstances`
2. `lambda:CreateFunction` and `lambda:UpdateFunctionConfiguration`
3. `codebuild:CreateProject` and `codebuild:UpdateProject` (documented [here](https://docs.aws.amazon.com/codebuild/latest/userguide/auth-and-access-control-permissions-reference.html) but not in the ARC page for CodeBuild)

I assume there are others but those are the ones I happened to be looking at. Not all of them are missing, including some of the lesser known services like `dax:CreateCluster` and `sms-voice:CreateConfigurationSetEventDestination`.

**Comment by copumpkin** [comment]
I started grepping all the AWS documentation for things that claim to use `PassRole` and got bored, but this is the list I have so far:

```
    'ec2:RunInstances',
    'ec2:ReplaceIamInstanceProfileAssociation',
    'ec2:AssociateIamInstanceProfile',
    'codebuild:CreateProject',
    'codebuild:UpdateProject'
    'lambda:CreateFunction',
    'lambda:UpdateFunctionConfiguration',
    'transfer:CreateUser',
    'sms-voice:CreateConfigurationSetEventDestination',
    'dax:CreateCluster',
    'shield:AssociateDRTRole',
    'ecs:RunTask',
    'events:PutRule',
    'events:PutTargets',
    'kinesisanalytics:CreateApplication'
```

**Comment by stephswo** [comment]
Excellent, thanks! I'm passing this to the IAM team so that they can poke all of the service teams to update their files. 

I think the key is that if a service uses a service-linked role to perform actions on behalf of customers, then the iam:PassRole permission is required.

**Comment by j2clerck** [comment]
@stephswo I just discovered myself that s3:PutBucketReplication API call is not referenced on the documentation, nor that it requires iam:PassRole on the replication role to work. The only error message was that s3:PutBucketReplication Access Denied which is a bit misleading.

**Comment by marcodiiga** [comment]
Ping for this: a lambda which sets up bucket replication and defines a replication role for S3 (as described in https://docs.aws.amazon.com/AmazonS3/latest/userguide/setting-repl-config-perm-overview.html#setting-repl-config-same-acctowner) needs that permission as well.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
