### ISSUE TITLE
Weird "example" for sts:ExternalId

### ISSUE THREAD

**Issue by copumpkin** [awsdocs/iam-user-guide#105]
If you check [this document on IAM condition keys](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_iam-condition-keys.html#condition-keys-sts), you'll see the following text:

> This value can be any string, such as a passphrase or account number. Because a cross-account role is usually set up to trust everyone in an account, the administrator of the trusting account might send an external ID to the administrator of the trusted account. That way, only someone with the ID can assume the role, rather than everyone in the account. 

This seems to be suggesting to add a role trust policy targeting an entire account and then to use the `ExternalId` as a secret to guard access, which isn't really the intended use and also isn't safe. Indeed, [the page it references right after that passage](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html) has a big loud warning right at the top telling users not to treat `ExternalId` as a secret:

> **Important**
>
> AWS does not treat the external ID as a secret. After you create a secret like an access key pair or a password in AWS, you cannot view them again. The external ID for a role can be seen by anyone with permission to view the role.

Can the documentation on [this page](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_iam-condition-keys.html#condition-keys-sts) be amended to not suggest an unsafe use of the field? Anyone with CloudTrail access could trivially circumvent the scheme described there. It seems better to immediately reference the confused deputy problem and tell people to read the longer page to learn more about it.

**Comment by stephswo** [comment]
You're right! I've updated the documentation to instead mention that the ExternalId is used to avoid the confused deputy problem. The docs will be live later today.

**Comment by copumpkin** [comment]
Thank you!
