### ISSUE TITLE
Allow or Deny access to individual actions in AWS Support

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/iam-user-guide#116]
https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awssupport.html

This is unclear. 

_The lines AWS Support does not let you allow or deny access to individual actions; therefore your policy must use the "Action": "support:*" to use the AWS Support Center or to use the AWS Support API._  and _You can specify the following actions in the Action element of an IAM policy statement. By using policies, you define the permissions for anyone performing an operation in AWS_ conflict with each other.  

On top of that, from the IAM policy console - it seems that I can actually list specific actions for support.

**Comment by megachromemonkey** [comment]
As mentioned previously here IAM does not have control over other services APIs/support for IAMs full set of features.  These files are dynamically generated based on information provided to the IAM team by other AWS services (in this case the AWS Support organization).  That being said when I opened a technical support case about this item I was told the following.

> The Support API is not currently written to correctly evaluate individual Support IAM actions; despite these actions having already been developed by Support.  For the time being if you want to use Support APIs you must only use support:* in your policies.  One more thing, Support API actions can only be paired with a resource value of "*".  Both of these issues are well known internally, and the AWS Support organization takes customer feedback seriously... 

From this response we need to point our pitchforks at the AWS Support team not IAM.  As for your second item, why doesn't the IAM policy editor detect this?  That's sounds like a bug and should be filed through your TAM or a Support case.

**Comment by stephswo** [comment]
Megachromemon... was on the nose.

**Comment by stephswo** [comment]
The Support team guidance is to specify all actions in a policy to allow or deny access.
"support:*"

Because they don't support the normal IAM model, they removed their page. They are making some changes within the service. When the page reappears, they will fully support the normal 1:1 relationship of policy actions to API operations.
