### ISSUE TITLE
kms:CreateAlias requires alias as a resource

### ISSUE THREAD

**Issue by michael-k** [awsdocs/iam-user-guide#119]
We tried to use the IAM action `kms:CreateAlias` with a key as a resource as specified here: https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awskeymanagementservice.html#awskeymanagementservice-actions-as-permissions

The Stack failed with:

    User: arn:aws:sts::***:assumed-role/***/AWSCloudFormation
    is not authorized to perform: kms:CreateAlias on resource:
    arn:aws:kms:eu-west-1:***:alias/***

After adding `alias/*` to the resources, everything worked as expected.

**Comment by stephswo** [comment]
I recommend surfacing this with the KMS team. 

The list of actions, resources, and conditions that we publish in the IAM user guide is automated based on content from each service. Beyond that, we can't help much with specific KMS issues. 

 You can reach them here: https://github.com/awsdocs/aws-kms-developer-guide/blob/master/doc_source/iam-policies.md
