### ISSUE TITLE
Missing conditions for AWS Systems Manager

### ISSUE THREAD

**Issue by michael-k** [awsdocs/iam-user-guide#122]
According to https://docs.aws.amazon.com/systems-manager/latest/userguide/auth-and-access-control-iam-access-control-identity-based.html#policy-conditions, AWS Systems Manager supports the following condition keys:

- `ssm:resourceTag/*`
- `ssm:Recursive`
- `ssm:Overwrite`

But https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awssystemsmanager.html ([code](https://github.com/awsdocs/iam-user-guide/blob/master/doc_source/list_awssystemsmanager.md)) only mentions the first one.

**Comment by carlasp** [comment]
Thank you for your contribution. The IAM writer is out of the office until the end of June. She will address this when she returns.

**Comment by bonniekeller** [comment]
Reveiwing older issues and wanted to address this one. The page is updated from information that the Systems Manager team maintains. At some point, it was updated and now shows the condition keys you had reported as missing. Thanks so much for taking the time to submit the issue.
