### ISSUE TITLE
Incorrect Link for GetContextKeysForPrincipalPolicy 

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/iam-user-guide#123]
GetContextKeysForPrincipalPolicy on this page: https://docs.aws.amazon.com/IAM/latest/UserGuide/list_identityandaccessmanagement.html takes me to https://docs.aws.amazon.com/IAM/latest/APIReference/Welcome.html where it should take me to the API reference for iam:GetContextKeysForPrincipalPolicy (which is here: https://docs.aws.amazon.com/IAM/latest/APIReference/API_GetContextKeysForPrincipalPolicy.html)

**Comment by carlasp** [comment]
Thank you for your contribution. The IAM writer is out of the office until the end of June. She will address this when she returns.

**Comment by bonniekeller** [comment]
Cleaning up some of the older issues in this repo, apologies for the delayed response. I verified that this link was fixed and now goes to https://docs.aws.amazon.com/IAM/latest/APIReference/API_GetContextKeysForPrincipalPolicy.html.
