### ISSUE TITLE
Missing Description for s3:ObjectOwnerOverrideToBucketOwner

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/iam-user-guide#124]
This permission is missing a description and also does not have a link to the API documentation either. 

I did find the following referencing ObjectOwnerOverrideToBucketOwner: https://docs.aws.amazon.com/AmazonS3/latest/dev/crr-change-owner.html

**Comment by carlasp** [comment]
Thank you for your contribution. The IAM writer is out of the office until the end of June. She will address this when she returns.

**Comment by foxnextben** [comment]
Looking for this as well.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
