### ISSUE TITLE
Missing "CanonicalUser" in principal_map_entry in IAM policy grammar

### ISSUE THREAD

**Issue by pkazmier** [awsdocs/iam-user-guide#128]
On this page:

https://github.com/awsdocs/iam-user-guide/blob/master/doc_source/reference_policies_grammar.md

the following grammar:

```
<principal_map_entry> = ("AWS" | "Federated" | "Service") :   
    [<principal_id_string>, <principal_id_string>, ...]
```

is missing `"CanonicalUser"` as a valid entry per this page:

https://github.com/awsdocs/iam-user-guide/blob/master/doc_source/reference_policies_elements_principal.md

**Comment by stephswo** [comment]
Good point. It's worth mentioning that the canonical user ID can be used only in S3 bucket policies. But thanks, I'll add it!
