### ISSUE TITLE
Services Compatible With iam:PassedToService?

### ISSUE THREAD

**Issue by machtvoll** [awsdocs/iam-user-guide#130]
Talking with AWS Premium Support they confirmed that the Lambda & CloudFormation services are not compatible with the condition **iam:PassedToService**.  Reviewing the document [Available Keys for IAM](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_iam-condition-keys.html) _(scroll down to iam:PassedToService)_ there's no mention of compatible/non-compoatible services.

Could this document be updated to reflect the list of compatible/non-compatible services.  If not is there an ETA for when this information will be made public so folks can avoid spending weeks with Support to learn service X isn't compatible?  

Else can we have a blurb that says might not work with some services, which arguably isn't much better but sets a flag that maybe the issue with ones policy is a bad service?

**Comment by stephswo** [comment]
I know that we can't provide a list of services that are compatible with the key. IAM can't control how or whether a service implements features, and they don't notify us. There are currently 184 services.

However, you're right that we can say that it doesn't work with all services. I'm going to check with the IAM team to learn under exactly what conditions customers can use this key. For example, I would expect iam:PassedToService to work only for services that support service roles (not service-linked roles). Therefore I would think that if you allow passing only to a single service, this should stop that ability for all other services, if they support it. I'll dig deeper into this. Thanks!

**Comment by avoidik** [comment]
hello @stephswo did the IAM team provide any response about supported services?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
