### ISSUE TITLE
Cloudformation Support for Resource-Based Policies

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/iam-user-guide#132]
Based off this page (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/protect-stack-resources.html): Cloudformation does support stack policies.

On this page (https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_aws-services-that-work-with-iam.html#management_svcs), the chart shows CloudFormation not supporting resource-based policies.

I know Cloudformation does support stack policies, are these not considered "true" resource-based policies or should this chart be updated? 

Thanks!

**Comment by stephswo** [comment]
Thanks! I'll check with the Cloudformation team and verify whether the IAM page needs updating.

**Comment by harsha-akronym** [comment]
Hi, can we get an update on this?

**Comment by O330oei** [comment]
update

**Comment by bubblez79** [comment]
L

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
