### ISSUE TITLE
Content Missing on Policy Element: NotAction

### ISSUE THREAD

**Issue by ryanliu1021** [awsdocs/iam-user-guide#147]
The last paragraph of the document, "IAM JSON Policy Elements: NotAction" mentioned "The following example policy denies access to..." However, there is no example provided after this paragraph.

The path to the doc file in this repository:
iam-user-guide/doc_source/reference_policies_elements_notaction.md

The URL to the doc is:
https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_notaction.html

**Comment by stephswo** [comment]
Thanks so much for finding and reporting this. We're fixing it now and you'll see the changes in a bit.
