### ISSUE TITLE
AWS Global Condition Context Keys

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/iam-user-guide#160]
I see on this page https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_variables.html that the ec2:SourceInstanceARN key is present only when the request comes from an Amazon EC2 instance using an IAM role associated with an EC2 instance profile.  

Looking at some of the other global condition keys, where some have availability disclaimers, could ec2:sourceInstanceARN also be considered a global condition key?

, https://github.com/awsdocs/iam-user-guide/blob/master/doc_source/reference_policies_condition-keys.md

**Comment by bonniekeller** [comment]
Hello, thanks for your question. We are looking into whether this key should be considered a global condition key. I'll follow up with you as soon as I have additional information.

**Comment by bonniekeller** [comment]
We've confirmed that this key can be considered a Global Condition Key. I've added a backlog item to update the page. We'll keep this issue open until we are able to make the update.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
