### ISSUE TITLE
MFA resource type format incorrectly documented

### ISSUE THREAD

**Issue by 0xdabbad00** [awsdocs/iam-user-guide#161]
Based on https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_aws_my-sec-creds-self-manage.html the action `iam:CreateVirtualMFADevice` is given a Resource of `arn:aws:iam::*:mfa/${aws:username}`, but in the docs, this action is stated to require a resource of the format `arn:${Partition}:iam::${Account}:mfa/${Path}/${MfaTokenId}` (see https://docs.aws.amazon.com/IAM/latest/UserGuide/list_identityandaccessmanagement.html#identityandaccessmanagement-mfa).

The discrepancy is with the part `${aws:username}` vs `${Path}/${MfaTokenId}` where the latter requires a `/`, but the former does not.  The action `iam:CreateVirtualMFADevice` does not require an MFA resource with that additional `/` in it, and therefore the docs are incorrect.  This is in the file https://github.com/awsdocs/iam-user-guide/blob/1e13dd780146c57701c6069ba0b9bd185a6f13d6/doc_source/list_identityandaccessmanagement.md#L41

**Comment by bonniekeller** [comment]
You're correct that there is not an extra required `/`. The example policy here is correct for iam:CreateVirtualMFADevice: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_aws_my-sec-creds-self-manage.html. We need to engage with the IAM engineering team to confirm and determine what updates are required.

**Comment by 0xdabbad00** [comment]
Any updates on this?

**Comment by bonniekeller** [comment]
We sent a ticket to the engineering team and we are awaiting their feedback.

**Comment by 0xdabbad00** [comment]
Any updates? It's been over 2 months since this was reported.

**Comment by bonniekeller** [comment]
Hi, sorry for the delay and thanks again for reporting this. The engineering team is engaged and plans to make an update to this portion of the documentation. As soon as I know when it will be scheduled, I'll provide an other update.

**Comment by 0xdabbad00** [comment]
Any updates on this?

**Comment by bonniekeller** [comment]
I have requested an updated status from the engineering teams involved with this request.

**Comment by bonniekeller** [comment]
Apologies for the long delay. The MFA resource ARN format has now been updated. Thanks so much for reporting this.
