### ISSUE TITLE
aws:PrincipalOrgPaths examples incorrect

### ISSUE THREAD

**Issue by seittema** [awsdocs/iam-user-guide#162]
The examples for the aws:PrincipalOrgPaths on the AWS Global Condition Context Keys page are incorrect and can cause a lot of headache if you aren't familiar with IAM.  
All the examples use ForAnyValues:**** however ForAnyValues is not a valid set operator, it should be ForAnyValue (not plural) according to https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_multi-value-conditions.html#reference_policies_multi-key-or-value-conditions

Unfortunately the user guide here doesn't appear to be the most recent otherwise I would put in a PR to fix it.

**Comment by bonniekeller** [comment]
Great catch! Thanks so much for pointing this out! I'm pushing a fresh version of the user guide to GitHub today, but this won't be fixed with that push. I've cut an internal ticket to fix this once we are able to publish updates to the public website again during the week of 12/8.

**Comment by bonniekeller** [comment]
This has been updated in the public docs so I'm closing this issue.

**Comment by bonniekeller** [comment]
Closing after update.
