### ISSUE TITLE
es:CreateElasticsearchServiceRole missing from Elasticsearch service actions

### ISSUE THREAD

**Issue by andywickersham** [awsdocs/iam-user-guide#163]
The Elasticsearch documentation is missing the "es:CreateElasticsearchServiceRole" action which is required when creating a new Elasticsearch domain.

Documentation URL:
https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonelasticsearchservice.html

**Comment by jsoncow** [comment]
Hi Andy!

To create a ServiceRole for Elasticsearch, this is tied to the IAM action iam:CreateServiceLinkedRole.

It's interesting.  There is es:DeleteElasticsearchServiceRole for a manual deletion of the ES Service Role, but the create is handled by an API action that falls under the broader IAM service umbrella.

https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/slr-es.html

**Comment by andywickersham** [comment]
This is the CloudTrail error:
User: arn:aws:sts::[ACCOUNT ID]:assumed-role/SecurityOperations/[USER] is not authorized to perform: es:CreateElasticsearchServiceRole on resource: arn:aws:es:us-east-1:[ACCOUNT ID]:domain/*

This is the IAM policy statement that fixed it:
            Sid: AllowESRoleCreate
            Effect: Allow
            Action:
              - es:CreateElasticsearchServiceRole
            Resource: !Sub arn:${AWS::Partition}:es:${AWS::Region}:${AWS::AccountId}:domain/*/*

**Comment by jsoncow** [comment]
Interesting!  

You're right.  I see it in my CloudTrail as well now.  

@AWS, this should be fixed in the ES User Guide as well.  https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/slr-es.html

**Comment by bonniekeller** [comment]
Thank you for bringing this to our attention. The information on this page https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonelasticsearchservice.html is generated automatically with information provided by the Elastic Search team. I've cut the Elastic Search service team a ticket to review your issue. Someone from the service team will get back to you about this issue.
