### ISSUE TITLE
EC2 image builder IAM documentation missing

### ISSUE THREAD

**Issue by atkinsonm** [awsdocs/iam-user-guide#164]
https://github.com/awsdocs/ec2-image-builder-user-guide/blob/master/doc_source/security_iam_service-with-iam.md references [doc_source/reference_policies_actions-resources-contextkeys.md](doc_source/reference_policies_actions-resources-contextkeys.md) for IAM actions:

> To see a list of Image Builder actions, see Actions, Resources, and Condition Keys for AWS Services in the IAM User Guide.

However, EC2 Image Builder with the `imagebuilder` namespace is not represented in the list of services.

**Comment by bonniekeller** [comment]
Hello, thanks for taking the time to provide feedback. AWS released a lot of new features ans services this week at re:Invent. This is one of those services. You should see updates to the public documentation early next week (week of 12/9).

**Comment by atkinsonm** [comment]
@bonniekeller thanks for your response. I fully appreciate the amount of effort in front of the team from re:Invent announcements. If this was a situation where I was simply looking for something and not finding it, I would understand. My challenge is that the EC2 Image Builder documentation clearly references the page I linked as if it exists, but it does not. It's abstract to me as a non-amazonian whether this type of document is managed by the service team, the IAM team, or both.

Thanks again for your response and I look forward to checking out the detailed docs once available.

**Comment by bonniekeller** [comment]
Hi Mike, I apologize for the inconvenience. Each documentation set is managed by the the respective writing team. During re:Invent, we observe restrictions that limit what can be published. Thanks so much for undertsanding. You can now find the information you are looking for here: https://github.com/awsdocs/iam-user-guide/blob/master/doc_source/list_amazonec2imagebuilder.md or at https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonec2imagebuilder.html in our public documentation.

**Comment by atkinsonm** [comment]
Completely understood. Thanks for the explanation and the quick turnaround!
