### ISSUE TITLE
 Wildcards DO span resource ARN segments in policies

### ISSUE THREAD

**Issue by madmox** [awsdocs/iam-user-guide#175]
The documentation on "[IAM JSON Policy Elements: Resource](https://github.com/awsdocs/iam-user-guide/blob/master/doc_source/reference_policies_elements_resource.md)" states (also [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_resource.html)):

> You can use wildcards as part of the resource ARN. You can use wildcard characters (* and ?) within any ARN segment (the parts separated by colons). An asterisk (*) represents any combination of characters and a question mark (?) represents any single character. You can use multiple * or ? characters in each segment, but **a wildcard cannot span segments**. The following example refers to all IAM users whose path is /accounting.

I checked in the [policy simulator](https://policysim.aws.amazon.com/) and the part on wildcards not spanning segments seems to be wrong.

Policy:
```json
{
  "Version": "2012-10-17",
  "Statement": [{
    "Effect": "Allow",
    "Action": "s3:GetObject",
    "Resource": "arn:aws:s3:::my-bucket/foo/*/bar"
  }]
}
```
With the above policy, the user is granted access to `arn:aws:s3:::my-bucket/foo/1/2/bar`. So the wildcard DOES span ARN segments.

I believe this could lead to serious security issues in organization relying on the documented behavior. An example of such misconfiguration would be `arn:aws:s3:::my-bucket-*/public/*`. In this case, the policy matches `arn:aws:s3:::my-bucket-prod/private/public/*` - this is unexpected.

**Comment by copumpkin** [comment]
The segments mentioned in that passage are the colon-delimited segments, and your example lives entirely in the final segment. From your quote:

> within any ARN segment (the parts separated by colons)

It is true that wildcards can span across slashes in S3 paths, but I don't think the documentation says otherwise. Am I misunderstanding your point?

**Comment by madmox** [comment]
Oh, I skipped the part defining what is an ARN segment and assumed it was the same thing as an URI path segment (as ARN are URI).

**Comment by bonniekeller** [comment]
Thanks so much for your comment. I hope this cleared up your question. I will close this issue.
