### ISSUE TITLE
Is `aws:ResourceTag` really a `global condition key` for IAM Policy?

### ISSUE THREAD

**Issue by samit2040** [awsdocs/iam-user-guide#177]
I am trying to create an IAM policy that **Deny** access to an ec2 instance if a particular tag is attached with the resources.

``` 
policy.json

{
......
      "Effect": "Deny",
      "Resource": "*",
      "Condition": {
        "StringEquals": {
            "aws:ResourceTag/foo":"bar" 
        }
      }
.....
```

EC2 only has **ec2:ResourceTag** rather than **aws:ResourceTag**

Is **aws:ResourceTag** really a **global condition key**? 

Some services does create service-specific tags with **aws:** prefix  like **ECR ,RDS** .
while there some services like **S3 , EC2** which **doesn't create tags with aws: prefix**

I found a [stackoverflow post](https://stackoverflow.com/questions/58993574/iam-policy-with-awsresourcetag-not-supported) related to it.

The document on [AWS Global Condition Context Keys](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html) is quite a bit misleadings and needs to be updated or I am following it in a different way.

**Comment by bonniekeller** [comment]
You are correct. aws:ResourceTag is a global condition key that is available for all services to use. Some services, such as IAM and EC2, support only the service-specific version of this key and not the global version. For more information, see https://docs.aws.amazon.com/IAM/latest/UserGuide/access_tags.html#access_tags_control-resources. 

To see which services support this key, you can check the Authorization Based on Tags column in the table on this page https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_aws-services-that-work-with-iam.html. In order for the service to support tag-based authorization, they must support this key.  

We'll add a little bit of clarity to the documentation.
