### ISSUE TITLE
cloudtrail.amazonaws.com works for aws:CalledVia in a bucket policy

### ISSUE THREAD

**Issue by andywickersham** [awsdocs/iam-user-guide#180]
The below bucket policy works with aws:CalledVia and cloudtrail.amazonaws.com. Removing the second condition prevents CloudTrail from sending logs to the bucket.

Is there a way to confirm that cloudtrail.amazonaws.com is now supported with aws:CalledVia?

```
{
            "Sid": "DenyExternalPrincipals",
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::aws-landing-zone-org-trail-logs-[ACCOUNT ID]-us-east-1",
                "arn:aws:s3:::aws-landing-zone-org-trail-logs-[ACCOUNT ID]-us-east-1/*"
            ],
            "Condition": {
                "StringNotEquals": {
                    "aws:PrincipalOrgID": "[ORG ID]"
                },
                "ForAnyValue:StringNotEquals": {
                    "aws:CalledVia": "cloudtrail.amazonaws.com"
                }
            }
        },
```

**Comment by bonniekeller** [comment]
Thanks for your question. I'll check with the IAM team to see if they can confirm that it should work. If it does, I will update the list of supported services in our documentation: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-calledvia.

**Comment by bonniekeller** [comment]
Thanks again for your question. The services listed in the documentation represent the services we support. We do not recommend using the key with any service that is not listed as supported. We will keep the documentation up to date with the list of supported services.
