### ISSUE TITLE
Incorrect action list for SQS

### ISSUE THREAD

**Issue by qidydl** [awsdocs/iam-user-guide#181]
The IAM documentation lists the Batch versions of SQS actions as separate items, but SQS no longer allows these to be permissioned independently, as seen in their permissions reference: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-api-permissions-reference.html

Attempting to use these permissions will result in an error:

> Value sqs:ChangeMessageVisibilityBatch for parameter ActionName is invalid. Reason: Please refer to the appropriate WSDL for a list of valid actions.

**Comment by bonniekeller** [comment]
I think you might be referring to the information on this page: https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonsqs.html. Can you tell me which actions you are referring to? The information on these pages of the IAM documentation comes from data that each service provides. If it is incorrect, I will pass a ticket over to the SQS team to update their information.

**Comment by qidydl** [comment]
Yes, that's the right link, sorry I forgot to point to the specific IAM docs page.

SQS does not support permissions for the ChangeMessageVisibilityBatch, DeleteMessageBatch, or SendMessageBatch actions. Those API calls exist, but access is controlled via permission to the ChangeMessageVisibility, DeleteMessage, and SendMessage actions, respectively.

**Comment by bonniekeller** [comment]
Thanks for confirming. I sent a ticket over to the SQS team to review your comments and update the file that generates this page of the documentation, if necessary. Our internal TT# is V192150586.
