### ISSUE TITLE
Quicksight:CreateVPCConnection

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/iam-user-guide#187]
https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonquicksight.html

Looking over the API Calls, I don't see quicksight:CreateVPCConnection but see it called out here: https://docs.aws.amazon.com/quicksight/latest/user/working-with-aws-vpc.html.

Thanks!

**Comment by bonniekeller** [comment]
Hi there, thanks for the feedback. Unfortunately, this isn't a page in the IAM user guide. Are you expecting to see something for this in the IAM documentation?

**Comment by jsoncow** [comment]
Thanks, edited and linked the page: https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonquicksight.html

**Comment by bonniekeller** [comment]
Thanks! Unfortunately, this information on this page is provided and maintained by the service team, though it does appear within the IAM docs. All of the pages in the Actions, Resources, and Condition keys section are this way. I'll send a ticket over to the Quicksight team, but they don't use GitHub for tracking or replying to those types of issues. Note that not all API calls correlate 1:1 with actions and this might be the reason why. One thing you can do is leave feedback with your question on one of the Quicksight pages on docs.aws.amazon.com, like the original link that you provided, https://docs.aws.amazon.com/quicksight/latest/user/working-with-aws-vpc.html and the Quicksight writer will receive it and respond to you.

**Comment by bonniekeller** [comment]
Our internal TT# is V201043721, in case you want to leave that in your feedback on a Quicksight page.
