### ISSUE TITLE
Actions, resources, and condition keys for ECS capacity providers missing

### ISSUE THREAD

**Issue by bryanburke** [awsdocs/iam-user-guide#189]
[Actions, Resources, and Condition Keys for Amazon Elastic Container Service](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonelasticcontainerservice.html) is missing the API actions, resources, and condition keys for capacity providers.

**Comment by bonniekeller** [comment]
Hi, thanks for the feedback. These pages are automatically generated from information that the ECS service team provides to IAM. I'll open a ticket to the ECS team if you can give me more information about what's missing.

**Comment by bryanburke** [comment]
@bonniekeller The page is missing the following API actions:

* [CreateCapacityProvider](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CreateCapacityProvider.html)
* [DescribeCapacityProviders](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DescribeCapacityProviders.html)
* [PutClusterCapacityProviders](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_PutClusterCapacityProviders.html)

It is also missing the `capacity-provider` resource type with its associated ARN and (perhaps) conditions.

**Comment by bonniekeller** [comment]
I created an internal ticket for the ECS team for this issue: #V206775477. The ECS service team are the only ones who can review your feedback and update the information on the page, if necessary.
