### ISSUE TITLE
Strange enumeration in id_users_change-permissions.html

### ISSUE THREAD

**Issue by commjoen** [awsdocs/iam-user-guide#194]
Thank you for the extensive documentation! One minor issue while reading: the ` id_users_change-permissions.html` says: 

```
IAM offers three ways to change permissions that are associated with a user:
```
and then offers only 2 options, but the sub-paragraphs show 3 deletion methods as well. What would be the recommended take on this? Would you prefer listing deletion as the third option, or change the sentence from `three` to `two`?

**Comment by bonniekeller** [comment]
Thanks for bringing this to our attention. I have made an edit to clarify that. It should be visible later today.
