### ISSUE TITLE
Amazon Elasticsearch Service - missing Action - StartElasticsearchServiceSoftwareUpdate

### ISSUE THREAD

**Issue by vincentclee** [awsdocs/iam-user-guide#197]
## 🐛 Bug Report

Amazon Elasticsearch Service Documentation is missing the action (`StartElasticsearchServiceSoftwareUpdate`). The primary purpose is to schedule a service software update for an Amazon ES domain.

## To Reproduce
Schedule a service software update for an Amazon ES domain via the CLI:
```
aws es start-elasticsearch-service-software-update --domain-name noforn-es-dev
```

## Error Output
```
+ aws es start-elasticsearch-service-software-update --domain-name noforn-es-dev

An error occurred (AccessDeniedException) when calling the StartElasticsearchServiceSoftwareUpdate operation: User: arn:aws:sts::1484931600:assumed-role/us_cyber_com_iam_role/Jenkins-Elasticsearch-Utilities-Elasticsearch-1 is not authorized to perform: es:StartElasticsearchServiceSoftwareUpdate on resource: arn:aws:es:us-east-1:1484931600:domain/noforn-es-dev
```

### Links
* https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonelasticsearchservice.html
* https://github.com/awsdocs/iam-user-guide/blob/master/doc_source/list_amazonelasticsearchservice.md
* https://docs.aws.amazon.com/cli/latest/reference/es/start-elasticsearch-service-software-update.html

**Comment by bonniekeller** [comment]
I opened an internal ticket to the Amazon Elastic Search service team TT# V223276530
