### ISSUE TITLE
Session tags page uses non-standard ASCII dashes

### ISSUE THREAD

**Issue by mechanomancy** [awsdocs/iam-user-guide#199]
On the page [session tags](https://github.com/awsdocs/iam-user-guide/blob/master/doc_source/id_session-tags.mdl), some of the tag CLI references use non-standard ASCII dashes which cause an error when copying and pasting locally.

For example in this block from the page;
```shell
aws sts assume-role \
--role-arn arn:aws:iam::123456789012:role/Role1 \
--role-session-name Session1 \
–-tags Key=Star,Value=1 Key=Heart,Value=1 \
--transitive-tag-keys Star Heart
```

The first dash on `–-tags` is actually ASCII character `U+00E2 LATIN SMALL LETTER A WITH CIRCUMFLEX character (&#x00E2;)` instead of `U+002D HYPHEN-MINUS character (-)`. 

When pasted into CLI this results in the following error:
```shell
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: Key=Star,Value=1, –-tags
```

Obviously ideally a user should retype commands for security but on occasion copy and paste is faster and easier.

**Comment by bonniekeller** [comment]
Thanks for reporting this. I will fix this and publish an update as soon as possible. ETA week of 7/20 due to publishing cadence.

**Comment by bonniekeller** [comment]
Thanks again for reporting this, the fix is live in the documentation.
