### ISSUE TITLE
why iam ABAC not work on s3 or ec2vpc etc.

### ISSUE THREAD

**Issue by hk1313** [awsdocs/iam-user-guide#202]
i tried tutorial from https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_attribute-based-access-control.html.   works fine as well. but

when i do same thing for other aws services like S3, ec2VPC ( as i don't want to see all vpc to all users), aws rekognition etc, it does not work.

**Comment by bonniekeller** [comment]
Thanks for the question. I don't know the answer but I am checking with the service team.

**Comment by bonniekeller** [comment]
Attribute-based access control will work for services that support Authorization based on tags (as per https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_aws-services-that-work-with-iam.html), and we are actively working on supporting tag-based access control uniformly across all services.
