### ISSUE TITLE
CloudWatch Logs documentation is missing IAM actions

### ISSUE THREAD

**Issue by rclark** [awsdocs/iam-user-guide#204]
https://github.com/awsdocs/iam-user-guide/blob/master/doc_source/list_amazoncloudwatchlogs.md

The actions table doesn't include `PutQueryDefinition` or `DescribeQueryDefinitions`, two IAM actions that are documented in [CloudWatch Log's User Guide](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AnalyzingLogData.html) as required in order to use a feature for saving Log Insights queries that was [released in May](https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-cloudwatch-logs-insights-now-allows-you-to-save-queries/).

Here we are, 3 months later, and the IAM documentation does not describe the new actions. I don't understand why AWS perpetually allows features to launch without definitively documenting the IAM permissions required to use those features.

**Comment by bonniekeller** [comment]
Hi, thanks for the feedback. I apologize for the frustration. Each AWS service owns code that automatically generates the actions, resource, and condition key information that appears for that service in the IAM User Guide. The service team has to make the update to their code so this information is present on the page. I've created a ticket with your feedback and assigned it to the service team. Internal ticket# V222119362.
