### ISSUE TITLE
roles-managingrole-editing-console seems to be out-of-sync

### ISSUE THREAD

**Issue by tdmalone** [awsdocs/iam-user-guide#206]
It was recently announced that assumed roles in the console are now valid for up to 12 hours.

This paragraph is available at https://docs.aws.amazon.com/IAM/latest/UserGuide/roles-managingrole-editing-console.html#roles-modify_max-session-duration:
> In the AWS Management Console, IAM user sessions are 12 hours by default. IAM users switching roles in the console are granted the role maximum session duration, or the remaining time in the IAM user's session, whichever is less.
> 
> Anyone who assumes the role from the AWS CLI or AWS API can request a longer session, up to this maximum. The MaxSessionDuration setting determines the maximum duration of the role session that can be requested.
> 
> To specify a session duration using the AWS CLI use the duration-seconds parameter. To learn more, see Switching to an IAM Role (AWS CLI).
>
> To specify a session duration using the AWS API, use the DurationSeconds parameter. To learn more, see Switching to an IAM Role (AWS API).

But the same paragraph appears to be missing from https://github.com/awsdocs/iam-user-guide/blob/master/doc_source/roles-managingrole-editing-console.md#modifying-a-role-maximum-session-duration-console, which means that edits to it can't be suggested.

**Comment by bonniekeller** [comment]
Thanks for the feedback. We refresh our GitHub content manually periodically. I will be refreshing it today. The content will be in sync after I've completed that. You can also leave documentation feedback on any page of the AWS Documentation website by choosing the Feedback button on the top right of the page. Here's a link to the page you mentioned: https://docs.aws.amazon.com/IAM/latest/UserGuide/roles-managingrole-editing-console.html#roles-modify_max-session-duration. The feedback you leave gets routed to the writing team for the service.

**Comment by bonniekeller** [comment]
Content has been refreshed.
