### ISSUE TITLE
Missing Links in Actions in CloudFormation Actions Table: TagResource and UntagResource

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/iam-user-guide#209]
Hi!  

On this action page: https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awscloudformation.html, I see TagResource ad UntagResource.  However, these do not link like the other actions and also are not listed here: https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/Welcome.html.

Are these still valid API calls?

**Comment by bonniekeller** [comment]
Hi, thanks for taking the time to ask this question. I sent a ticket over to the service team. Each AWS service maintains their own file that generates the information on this documentation page. They are the only ones who can update the information. I provided them a link to this GitHub issue, but they may not reach back out to you here about it. Internal ticket #P41744266.
