### ISSUE TITLE
Links to CloudFront Actions are broken

### ISSUE THREAD

**Issue by michael-k** [awsdocs/iam-user-guide#212]
On https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazoncloudfront.html#amazoncloudfront-actions-as-permissions the links to the actions are broken.  Eg. the link for `CreateCloudFrontOriginAccessIdentity`:

```diff
-https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_Operations.html/API_CreateCloudFrontOriginAccessIdentity.html
+https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CreateCloudFrontOriginAccessIdentity.html
```

I know that this the CloudFront team's responsibility, but I don't know how to report this directly to them.  Please forward the issue. :)

**Comment by bonniekeller** [comment]
Hi Michael, thanks a lot for reporting this issue. It's easier for us if you report these issues using the HTML version of the docs website, but since you are using GitHub, I can also create a new ticket and pass it over to the CloudFront team to resolve. Thank you!
