### ISSUE TITLE
guardduty:DescribePublishingDestination does not work with documented resources

### ISSUE THREAD

**Issue by andywick-aws** [awsdocs/iam-user-guide#218]
The GuardDuty IAM docs list detector* and publishingdestination* as resources that can be used for guardduty:DescribePublishingDestination. 

Error: (Notice the :/detector/ in the expected resource ARN)
DescribePublishingDestination: User: arn:aws:sts::ACCOUNTID:assumed-role/ROLE/USER is not authorized to perform: guardduty:DescribePublishingDestination on resource: arn:aws:guardduty:us-east-1:ACCOUNTID:/detector/DETECTORID/publishingDestination/PUBLISHINGDESTINATION

This works but is not aligned with the docs:

"Resource": [
                "arn:aws:guardduty:*:ACCOUNTID:/detector/*",
                "arn:aws:guardduty:*:ACCOUNTID:detector/*/threatintelset/*"
            ]

**Comment by bonniekeller** [comment]
Thanks for reporting this issue. The information on these pages in the IAM docs is generated automatically from code that the Guard Duty team owns. I sent a ticket to them for this issue and the other that you opened https://github.com/awsdocs/iam-user-guide/issues/217.
