### ISSUE TITLE
Typo in “Actions, resources, and condition keys for AWS CloudFormation”

### ISSUE THREAD

**Issue by sftim** [awsdocs/iam-user-guide#223]
https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awscloudformation.html#awscloudformation-policy-keys contains a typo; “Documenation” should, I think, be “Documentation”.

**Comment by bonniekeller** [comment]
Hi! Thanks so much for taking the time to leave this feedback. I don't see this typo on the page any longer so I think it has already been resolved.
