### ISSUE TITLE
Was it intentional that all list_* files have been wiped?

### ISSUE THREAD

**Issue by udondan** [awsdocs/iam-user-guide#225]
With yesterdays periodic update all list_* files have been wiped. Was this intentional?

https://github.com/awsdocs/iam-user-guide/commit/0eb32aaa556788e1443e231d2b09d26a6ef9784b

**Comment by bonniekeller** [comment]
Yes, we moved these pages to a new guide, separate from the IAM User Guide. You can find them here: https://docs.aws.amazon.com/service-authorization/latest/reference/reference.html. All links for the all pages at the previous location have been permanently redirected to the new guide.

**Comment by udondan** [comment]
Yes, all but one, see https://github.com/awsdocs/iam-user-guide/issues/226 😸

**Comment by bonniekeller** [comment]
Thanks so much! Looking at that one now.
