### ISSUE TITLE
Missing redirect for appstream page

### ISSUE THREAD

**Issue by udondan** [awsdocs/iam-user-guide#226]
Yesterday all IAM documentation was moved from `https://docs.aws.amazon.com/IAM/latest/UserGuide/...` to `https://docs.aws.amazon.com/service-authorization/latest/reference/...`.

HTTP Redirects have been added, though one is broken, probably due to a regex not covering the dot in the file name, which is unique to `list_amazonappstream2.0.html`: https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonappstream2.0.html

**Comment by bonniekeller** [comment]
Thank you so much for finding this! I fixed that redirect.
