### ISSUE TITLE
aws:PrincipalOrgID global condition limitations

### ISSUE THREAD

**Issue by farski** [awsdocs/iam-user-guide#23]
https://github.com/awsdocs/iam-user-guide/blame/master/doc_source/reference_policies_condition-keys.md#L56

The docs do not mention the fact that the master account of an organization (which in other parts of the console/docs is considered or treated as a "member" of the org) won't match this condition.

**Comment by sinisterfrog** [comment]
Condition is working for my master & member accounts.  If there was an issue it’s resolved now.
