### ISSUE TITLE
Never put AWS temporary credentials in the credentials file (or env vars)—there’s a better way

### ISSUE THREAD

**Issue by ad-m** [awsdocs/iam-user-guide#249]
I think the examples on the use of "temporary credentials" (especially in the section "[Using temporary security credentials with the AWS CLI](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html#using-temp-creds-sdk-cli)") are cumbersome to actually use.

Could you apply @benkehoe 's feedback as outlined in https://ben11kehoe.medium.com/never-put-aws-temporary-credentials-in-env-vars-or-credentials-files-theres-a-better-way-25ec45b4d73e in documentation?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
