### ISSUE TITLE
Fix the documentation for Security Credentials

### ISSUE THREAD

**Issue by nick-kostov** [awsdocs/iam-user-guide#281]
The recent update of AWS Security credentials obliterated our terraform controlled set up.
Each time we want to add a user the Security Credentials page acts funny.
- States user already has MFA.
- User has MFA but MFA is from another user.
- What happened

**Comment by bonniekeller** [comment]
I'm sorry you're having trouble finding the information you need. If you have specific feedback on the docs that need to be fixed, we'd be happy to review that. For specific help with your issue, if you have purchased a support package, you can contact support here: https://aws.amazon.com/support/. Additionally, you can crowdsource your information or search for similar issues in our question and answer (Q&A) service AWS re:Post: https://repost.aws/. You might also need to reach out to Terraform for specific help with your issue https://www.terraform.io/.
