### ISSUE TITLE
Document constraints on Sid grammar

### ISSUE THREAD

**Issue by sourcefrog** [awsdocs/iam-user-guide#282]
According to 

    aws accessanalyzer validate-policy --policy-document policy.json --policy-type SERVICE_CONTROL_POLICY

the Sid can only have characters `[a-z, A-Z, 0-9]`.

At any rate a Sid containing underscores is rejected by the API.

It would be nice if the correct constraints were in https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_id.html.

Thank you @ransford!

**Comment by ljquin** [comment]
Hello @sourcefrog ,

The issue description mentions `Sid` but the provided link is for policy element `Id`. These are two different policy elements, `Sid` and `Id`. 

Can you clarify if you're referring to the `Sid` or `Id` policy element?


Reference links:
- https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_id.html

- https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_sid.html
>The Sid element supports ASCII uppercase letters (A-Z), lowercase letters (a-z), and numbers (0-9).
