### ISSUE TITLE
IAM doesn't have a detailed IAM reference for its own actions

### ISSUE THREAD

**Issue by copumpkin** [awsdocs/iam-user-guide#30]
I apologize if I somehow missed this, but comparing to [RDS](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAM.ResourcePermissions.html) or [EC2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-supported-iam-actions-resources.html), IAM isn't super clear about which resource-level permissions (and/or condition keys) apply to which API actions. The most I could find in the IAM user guide was some extended examples in [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_controlling.html), and a few more examples under [this heading](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_examples.html). But for example, if I want to know which resources (if any) apply to `iam:CreateRole` or whether I can scope `iam:GetRole` permissions to a particular role resource, I don't think that's mentioned anywhere except implicitly in the policy editor.

It would be really nice to get a similar table of all valid IAM actions, what resources they apply to, and which condition keys are relevant to them. This page could also make it clear that `GetCallerIdentity` is special and can't be restricted.

Or have I just missed a place where this material is covered?

Thanks!

**Comment by sinisterfrog** [comment]
IAM RLP doc can be found here:
https://docs.aws.amazon.com/IAM/latest/UserGuide/list_identityandaccessmanagement.html

RLP got every other service:
https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_actions-resources-contextkeys.html

**Comment by copumpkin** [comment]
Oh damn, I completely missed that somehow! Thanks and sorry for the noise 😄
