### ISSUE TITLE
Request for clarification on regional STS endpoints

### ISSUE THREAD

**Issue by copumpkin** [awsdocs/iam-user-guide#40]
In https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html, it talks extensively about what it means to enable or disable STS endpoints in a given region. The document says

> All regions are enabled by default, but you can disable any regions that _you know you don't need_.

at the top and that's what I find unclear. As an administrator of an account, it's unclear to me why I'd actually want to disable STS endpoints I don't need. Does disabling them come with a security benefit of some sort? Is it just a sense of cleanliness and efficiency of not leaving stuff turned on that I don't need?

Could the manual perhaps go into some detail about what kinds of scenarios might warrant disabling STS endpoints? I feel like a confused user might interpret disabling regional STS endpoints as disabling regions they don't use (which has valid use cases), which is definitely not the case.

**Comment by carlasp** [comment]
Thanks for your suggestion, @copumpkin. I've logged your request for possible inclusion in a future update of the doc.

**Comment by copumpkin** [comment]
Thanks!

**Comment by ozthegreat** [comment]
+1

**Comment by wiredin** [comment]
Its two years later and I'm still sitting here confused about that benefit deactivating regional STS endpoints provides. If it provides some sort of security or other benefit, that should be made clear. Or perhaps there is little benefit?
