### ISSUE TITLE
Warn that aws:UserAgent is just as untrustable as aws:Referer

### ISSUE THREAD

**Issue by copumpkin** [awsdocs/iam-user-guide#43]
I appreciated the big warning in the `aws:Referer` section of [this page](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html), explaining that it's provided through a remote HTTP header and thus does not provide a strong security guarantee.

It seems like a similar warning applies to `aws:UserAgent`, which currently just says "Checks the requester's client application", and thus might cause an unsuspecting IAM policy writer who is not familiar with how HTTP works to think it's somehow trustworthy.

**Comment by stephswo** [comment]
Thanks for pointing this out. I've updated the page and the changes will be live later today.
