### ISSUE TITLE
SecretsManager doc issue

### ISSUE THREAD

**Issue by 0xdabbad00** [awsdocs/iam-user-guide#45]
The secrets manager docs at https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awssecretsmanager.html  contain content not listed in this repo.  I noticed two mistakes.  In the row for `GetRandomPassword`, `passowrd` is spelled incorrectly, and the access level is listed as `write` instead of `read`.

**Comment by bisdavid** [comment]
Thanks for reporting this.  This topic is sourced from an internal file managed by the engineering teams.  I have reported this to them, and the fix should be included in an update release sometime next week.

**Comment by bisdavid** [comment]
Engineering team made the change to the file. This should find its way thru to the docs within a week.
