### ISSUE TITLE
Services actions don't separate by action type (list, read, write, permissions management)

### ISSUE THREAD

**Issue by yurymkomarov** [awsdocs/iam-user-guide#5]
It's very difficult to understand, what action type every action has.
This issue was created only for self-fixing this issue. I will create pull request with changes for two days.

With best regards, me!

**Comment by stephswo** [comment]
It's easier to find in the HTML docs.
- Actions sorted by service: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_actionsconditions.html
- Actions sorted first by action type, then by service: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_access-levels.html

The page in GitHub is here: https://github.com/awsdocs/iam-user-guide/blob/master/doc_source/reference_policies_access-levels.md
