### ISSUE TITLE
Image describes calling a role, which is confusing

### ISSUE THREAD

**Issue by edenhochbaum** [awsdocs/iam-user-guide#64]
[Example Scenario Using Separate Development and Production Accounts](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_aws-accounts.html) includes [this image](http://docs.aws.amazon.com/IAM/latest/UserGuide/images/roles-usingroletodelegate.png): 

![roles-usingroletodelegate](https://user-images.githubusercontent.com/8376351/47305220-65b39200-d5ee-11e8-9205-62698cbb5a11.png)

This language is inconsistent with other documentation, where roles are **assumed** and not **called**.

**Comment by edenhochbaum** [comment]
Additionally, the page is inconsistent on whether the role is **UpdateApp** or **UpdateAPP**, and role names are case-sensitive.

**Comment by stephswo** [comment]
You're right on both counts. I updated the docs and the changes should be live any minute now.
