### ISSUE TITLE
Request to consolidate global conditions keys

### ISSUE THREAD

**Issue by platform9-34th** [awsdocs/iam-user-guide#67]
The other day I came across two IAM documents discuss global condition keys:

- [AWS Global Condition Context Keys](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html)
- [IAM Policy Elements: Variables](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_variables.html#policy-vars-infotouse)

The document **AWS Global Condition Context Keys** seems to be the better choice for in depth information. Consider removing the conditions & their descriptions from **IAM Policy Elements: Variables** and just link to **AWS Global Condition Context Keys**?  

One more thing, the  document **IAM Policy Elements: Variables** has unique information that the condition **aws:UserAgent** should only be used with the AWS CLI and not for restricting a web browser:

`aws:UserAgent This value is a string that contains information about the requester's client application. This string is generated by the client and can be unreliable. You can only use this context key from the AWS CLI.`

Can we get this unique information added to **AWS Global Condition Context Keys**

**Comment by stephswo** [comment]
Excellent suggestions! I've added them to our backlog and hope to add them to the docs in the next few months.
