### ISSUE TITLE
List of all public service principal names

### ISSUE THREAD

**Issue by platform9-34th** [awsdocs/iam-user-guide#68]
There doesn't appear to be a document that lists all AWS services that can be defined in a service principal element of  trust policy.  A few that I'm aware of are:

- cloudtrail.amazonaws.com
- ec2.amazonaws.com
- config.amazonaws.com

The only way to get the service principal name that I've found are using the IAM console. Which I'll admit is not very direct and involves more steps than desired:

1. Log into the IAM console
2. Create an IAM role > select for use by a service
3. Open the role and view the trust policy

Having a document that lists all service principal names would be a killer feature, and allow us to self-service inquiries as to what service is being allowed.  As I'm sure not all service names are easy as ec2/cloudtrail/config.

**Comment by stephswo** [comment]
Thanks!

Unfortunately, there's no way today for IAM to know what all 140+ services choose to use for this field. We could manually compile a list of the ones that we know, but it would be incomplete and get out of date quickly.

We are aware of the problem and are looking for a solution. You're definitely not the first customer to ask. 

I can tell you that when I need to find a service principal, I look at this GitHub conversation: https://gist.github.com/shortjared/4c1e3fe52bdfa47522cfe5b41e5d6f22 
It's also out of date, but I've found that the ones I've used have been accurate.
