### ISSUE TITLE
Fix the MFA policy

### ISSUE THREAD

**Issue by 0xdabbad00** [awsdocs/iam-user-guide#75]
https://twitter.com/0xdabbad00/status/1068525426920710150

**Comment by stephswo** [comment]
It's fixed in Github!

**Comment by 0xdabbad00** [comment]
Re-open this ticket and please contact the AWS security team regarding my tweet. There are security issues that need to be fixed in 3 places in this repo.

**Comment by 0xdabbad00** [comment]
Looks like this has been resolved now in https://github.com/awsdocs/iam-user-guide/commit/f774f911164e539d336fbb47bf2f5f9634a36a90#diff-a01f9dbfc67cae4336ef8df70427f02f
