### ISSUE TITLE
Resolve out of date information for StartSession

### ISSUE THREAD

**Issue by melusom** [awsdocs/iam-user-guide#77]
## Description

[Sample IAM policies](https://docs.aws.amazon.com/systems-manager/latest/userguide/getting-started-restrict-access-examples.html#restrict-access-example-instance-tags) for Session Manager demonstrate instance id resource support as well as condition key support for the `StartSession` command. The IAM documentation for the action reflects neither. This can mislead developers into believing that `StartSession` must accompany `Resource: "*"` and will not support any conditions.

## Affected Files
- [doc_source/list_awssystemsmanager.md](../tree/master/doc_source/list_awssystemsmanager.md)

## References
- https://docs.aws.amazon.com/systems-manager/latest/userguide/getting-started-restrict-access-examples.html#restrict-access-example-instance-tags
- https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awssystemsmanager.html#awssystemsmanager-actions-as-permissions

## Proposed Resolution
- add `instance` to the resource types for `StartSession`
- add `ssm:resourceTag/tag-key` to the condition keys for `StartSession`
- add any other supported resource types or condition keys as appropriate

**Comment by melusom** [comment]
I would submit a PR but the actions table is not available in [doc_source/list_awssystemsmanager.md](doc_source/list_awssystemsmanager.md).

**Comment by melusom** [comment]
cc @grolston

**Comment by stephswo** [comment]
The  list of actions and conditions that we publish in the IAM user guide is automated based on content from each service. Thanks for letting us know that this service includes information that is not accurate. I will forward this information to the service's engineering team so that they can update the information.

**Comment by stephswo** [comment]
I did contact the service team, but there's no way to track that using GitHub. Keep an eye out for their changes.
