### ISSUE TITLE
Documentation does not include the new ecs tagging actions

### ISSUE THREAD

**Issue by melusom** [awsdocs/iam-user-guide#78]
## Description

[ECS API docs](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_Operations.html) and the [CLI ref](https://docs.aws.amazon.com/cli/latest/reference/ecs/index.html) have been updated to reflect new `TagResource` and `UntagResource` actions for ECS, but the IAM documentation has not.

## Affected Files
- [doc_source/aws-resource-ecs-cluster.md](../tree/master/doc_source/aws-resource-ecs-cluster.md)

## References
- https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_Operations.html
- https://docs.aws.amazon.com/cli/latest/reference/ecs/index.html

## Proposed Resolution
- add `TagResource` to the ECS IAM actions list
- add `UntagResource` to the ECS IAM actions list
- add supported resource types and condition keys as appropriate

Credit to @robertd for the discovery.

**Comment by melusom** [comment]
I would submit a PR but [doc_source/aws-resource-ecs-cluster.md](../tree/master/doc_source/aws-resource-ecs-cluster.md) does not contain the actions table.

**Comment by copumpkin** [comment]
On that note, could the actions be incorporated into this repo too? I'm guessing there's a post-processing step that adds them before publishing the documentation but as a user I'd vastly prefer seeing those complete actions tables in markdown than the HTML they're available in today.

**Comment by stephswo** [comment]
The  list of actions and conditions that we publish in the IAM user guide is automated based on content from each service. It can't be updated manually or by pull requests. Sorry.

Thanks for letting us know that this service includes information that is not accurate. I will forward this information to the service's engineering team so that they can update the information.

**Comment by copumpkin** [comment]
> The list of actions and conditions that we publish in the IAM user guide is automated based on content from each service

That makes sense. Is that machine-readable document published somewhere accessible to users? I have several use cases for something like that and have often wondered.

**Comment by stephswo** [comment]
Unfortunately, this data is not publicly available. If we ever do release the data, we will announce it in the Security Blog and on Twitter. I recommend that you follow one or both of those platforms to keep up with all of our releases. 

IAM category in the Security Blog: https://aws.amazon.com/blogs/security/category/security-identity-compliance/aws-identity-and-access-management-iam/

AWS Identity on Twitter: https://twitter.com/awsidentity
