### ISSUE TITLE
Documentation does not include all SSM actions

### ISSUE THREAD

**Issue by kmoschkau** [awsdocs/iam-user-guide#79]
# Description
SSM [API ](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_Operations.html) docs and the [CLI ](https://docs.aws.amazon.com/cli/latest/reference/ssm/index.html) ref include all available permissions, but the [IAM ](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awssystemsmanager.html) reference does not.

# Affected Files
doc_source/list_awssystemsmanager.md

# References
https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_Operations.html
https://docs.aws.amazon.com/cli/latest/reference/ssm/index.html

# Proposed Resolution
Add the following permissions to the IAM documentation:
- ssm:DescribeAutomationExecutions
- ssm:DescribeAutomationStepExecutions
- ssm:DescribeEffectiveInstanceAssociations
- ssm:DescribeInstanceAssociationsStatus
- ssm:GetCommandInvocation
- ssm:GetInventory
- ssm:GetInventorySchema
- ssm:ListDocumentVersions
- ssm:ListInstanceAssociations
- ssm:ListInventoryEntries
- ssm:ListResourceDataSync
- ssm:PutInventory
- ssm:StartAssociationsOnce
- ssm:UpdateAssociation
- ssm:UpdateDocument
- ssm:UpdateDocumentDefaultVersion
- ssm:UpdateInstanceAssociationStatus

**Comment by kmoschkau** [comment]
I would submit a PR but doc_source/list_awssystemsmanager.md does not contain the actions table.

**Comment by stephswo** [comment]
The  list of actions, resources, and conditions that we publish in the IAM user guide is automated based on content from each service. Thanks for letting us know that this service includes information that is not known to IAM. I will forward this information to the service's engineering team so that they can add the missing information.
