### ISSUE TITLE
Incorrect value documented for PermissionsBoundaryType

### ISSUE THREAD

**Issue by copumpkin** [awsdocs/iam-user-guide#82]
In the English text for [this documentation page](https://docs.aws.amazon.com/IAM/latest/APIReference/API_AttachedPermissionsBoundary.html), it says

>  This data type can only have a value of `Policy`.

However, a couple of lines down, it then claims

> Valid Values: `PermissionsBoundaryPolicy`

The former is correct. For example, calling `GetRole` on one of my roles with a boundary on it, returns

```json
        "PermissionsBoundary": {
            "PermissionsBoundaryType": "Policy",
            "PermissionsBoundaryArn": "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
        }
```

**Comment by stephswo** [comment]
Thanks! The incorrect info is coming from the model. I'll work with the IAM team to update the model.

**Comment by copumpkin** [comment]
Sounds good, thanks!

**Comment by sakitt** [comment]
Valid Values has been updated to address the reported issue.

Thanks for taking the time to send us feedback!
