### ISSUE TITLE
Comma missing in new MFA policy

### ISSUE THREAD

**Issue by 0xdabbad00** [awsdocs/iam-user-guide#87]
At https://github.com/awsdocs/iam-user-guide/commit/3a0537e1e4fcde8a57525c2e979e34554f7f6666#diff-fbf230b30ebe782d4a10b76ae6ad9b20R37 you need a comma after `"iam:GetAccountSummary"` otherwise the json is invalid.

**Comment by stephswo** [comment]
This is fixed, thanks!
