### ISSUE TITLE
IAM china wrong url for Switching role

### ISSUE THREAD

**Issue by ado2p** [awsdocs/iam-user-guide#91]
Hello at this link:
https://docs.amazonaws.cn/en_us/IAM/latest/UserGuide/id_roles_use_switch-role-console.html

You can manually construct the link and then skip to step Step 5 in the following procedure. To construct your link, use the following format:

https://signin.www.amazonaws.cn/switchrole?account=account_id_number&roleName=role_name&displayName=text_to_display

The url specification is wrong, it should be without "www":
https://signin.amazonaws.cn/switchrole?account=account_id_number&roleName=role_name&displayName=text_to_display

**Comment by stephswo** [comment]
Thanks! I've updated the documentation. It might take up to a couple of weeks for the Chinese version to be updated.
