### ISSUE TITLE
Documentation removed

### ISSUE THREAD

**Issue by willh** [awsdocs/iam-user-guide#93]
It appears in the latest periodic update that a large number of documentation files were removed: https://github.com/awsdocs/iam-user-guide/commit/2b1fa3805ebb57dfd1d9188ab1f5da7ee0a5b76c

For example the reference_policies_elements* files have gone, so the documentation for this page: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition.html appears to be missing.

**Comment by stephswo** [comment]
Thanks! We're investigating what happened so it doesn't happen again. The docs will be updated shortly.
