### ISSUE TITLE
Evaluating Identity-Based Policies with Resource-Based Policies

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/iam-user-guide#98]
From going through the Evaluating Identity-Based Policies with Resource-Based Policies, I noticed the following: _If an action is allowed by an identity-based policy, a resource-based policy, or both, then AWS allows the action._ 

However, that is not the case with KMS key policies.  

From KMS documentation (https://docs.aws.amazon.com/kms/latest/developerguide/control-access-overview.html):

For most AWS services, IAM policies are the only way to control access to the service's resources. Some services offer resource-based policies or other access control mechanisms to complement IAM policies, but these are generally optional and you can control access to the resources in these services with only IAM policies. This is not the case for AWS KMS, however. To allow access to a KMS CMK, you must use the key policy, either alone or in combination with IAM polices or grants. IAM policies by themselves are not sufficient to allow access to a CMK, though you can use them in combination with a CMK's key policy.

The policy evaluation logic should have a disclaimer that KMS does not function similarly and is an exception to the logic that is stated above (If an action is allowed by an identity-based policy, a resource-based policy, or both, then AWS allows the action)

**Comment by carlasp** [comment]
Thank you for your contribution. The IAM writer is currently away, and will address this when she returns.

**Comment by bonniekeller** [comment]
Thanks so much for your feedback. We recently added the KMS exception to the documentation. See #3, Resource-based policies: https://github.com/awsdocs/iam-user-guide/blob/main/doc_source/reference_policies_evaluation-logic.md#determining-whether-a-request-is-allowed-or-denied-within-an-account.
